[tool.poetry]
name = "asr"
version = "0.1.0"
description = ""
authors = ["Dima Lipin"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.9,<3.13"
openai-whisper = "^20231117"
faster-whisper = "^1.0.3"
aider-chat = "^0.55.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
